- .changeset/blue-dingos-carry.md
- packages/platform-apple-helpers/src/lib/commands/build/buildProject.ts
- packages/platform-apple-helpers/src/lib/commands/run/createRun.ts
- packages/platform-apple-helpers/src/lib/utils/buildApp.ts
For some reason using UDID works in some cases when using sim name with () doesn't work always, so let's use the matched device also use UDID.
`rnef run:ios --device "iPhone 16 Pro Max (iOS 18.4)"` should use UDID as a param in the `xcodebuild` command.
> fix: always use udid from matched device

- .changeset/tough-yaks-cry.md
- packages/platform-apple-helpers/src/lib/commands/build/createBuild.ts
- packages/platform-apple-helpers/src/lib/commands/run/createRun.ts
- packages/platform-apple-helpers/src/lib/utils/buildApp.ts
- packages/platform-apple-helpers/src/lib/utils/codegen.ts
- packages/platform-apple-helpers/src/lib/utils/pods.ts
- packages/platform-ios/src/lib/platformIOS.ts
- packages/plugin-brownfield-ios/src/lib/pluginBrownfieldIos.ts
This PR improves a few things:
- Runs codegen script, which is necessary for RN 0.79 apps. Fixes #173 
- Removes unnecessary retry of installing pods with "pod install" – we already run "bundler install" earlier, which if passes, we should be fairly certain it will also run `bundle exec pod install`. When it fails, we want to see the error as quickly as possible instead of retrying it with "pod install" which will most likely fail with the same error
- Improves error messages around pod version failure and others
> chore: improve error messages around installing pods; run codegen

- .changeset/little-kiwis-count.md
- packages/platform-android/src/lib/commands/runGradle.ts
- packages/platform-apple-helpers/src/lib/commands/build/buildProject.ts
- packages/platform-apple-helpers/src/lib/utils/getInfo.ts
Make it easier to parse information and shorten the "building" message to avoid a bug where a message longer than the terminal width would produce repeated output instead of clearing the buffer.
|iOS|Android|
|--|--|
|<img width="393" alt="Screenshot 2025-04-27 at 19 41 38" src="https://github.com/user-attachments/assets/9d6249db-326e-4f05-a07c-8e9b8d1c92a9" />|<img width="297" alt="Screenshot 2025-04-27 at 19 51 04" src="https://github.com/user-attachments/assets/4cabc51c-e87b-4c95-a899-8be39d2baf35" />|
> feat: structured build settings information

- .changeset/plenty-cooks-eat.md
- packages/platform-apple-helpers/src/lib/utils/codegen.ts
- packages/platform-apple-helpers/src/lib/utils/pods.ts
Fixes a bug where `build/generated/ios` folder for codegen would be generated inside root project instead of in `sourceDir`.
> fix: run codegen script in sourceDir

- website/docs/docs/remote-cache/github-actions/ios.md
This PR corrects a documentation error where an Android-specific command was mistakenly listed under the iOS section. The command has been updated to reflect the correct iOS usage.
> docs: Update iOS section with correct platform-specific command

- .changeset/late-students-allow.md
- packages/platform-android/src/lib/commands/buildAndroid/command.ts
- packages/platform-android/src/lib/commands/generateKeystore.ts
- packages/platform-android/src/lib/commands/runAndroid/command.ts
- packages/platform-android/src/lib/platformAndroid.ts
- packages/platform-ios/src/lib/platformIOS.ts
- packages/plugin-brownfield-ios/src/lib/pluginBrownfieldIos.ts
Loading iOS platform config when Android commands are run and vice-versa is unnecessary. This PR ads lazy loading to reading platform project config for auto linking purposes
> fix: lazy load autolinking platform config

- .github/actions/setup-node/action.yml
- .npmrc
- CONTRIBUTING.md
- package.json
- scripts/linkPackages.mjs
When deploying https://github.com/callstack/rnef/pull/208 we hit some weird issues related to pnpm version, in this PR I've added relevant configuration options which will ensure correct package manager and correct version will be used.
`pnpm install` works in the same way as before 👍
> fix: use strict package manager version

- .changeset/large-mirrors-confess.md
- packages/config/src/lib/schema.ts
- packages/tools/src/lib/__tests__/remoteBuildCache.test.ts
- packages/tools/src/lib/build-cache/common.ts
- packages/tools/src/lib/build-cache/fetchCachedBuild.ts
- packages/tools/src/lib/build-cache/github/GitHubBuildCache.ts
- packages/tools/src/lib/build-cache/github/artifacts.ts
- packages/tools/src/lib/build-cache/github/config.ts
- packages/tools/src/lib/build-cache/remoteBuildCache.ts
- packages/tools/src/lib/fingerprint/index.ts
- website/docs/docs/configuration.md
This diff adds support for writing your own custom remote providers, which was quasi-supported previously.
Notable changes: 
- Changed the remote cache interface to:
```ts
/**
* Interface for implementing remote build cache providers.
* Remote cache providers allow storing and retrieving native build artifacts (e.g. APK, IPA)
* from remote storage like S3, GitHub Artifacts etc.
*/
export interface RemoteBuildCache {
/** Unique identifier for this cache provider, will be displayed in logs */
name: string;
/**
* List available artifacts matching the given name pattern
* @param artifactName - Passed after fingerprinting the build, e.g. `rnef-android-debug-1234567890` for android in debug variant
* @param limit - Optional maximum number of artifacts to return
* @returns Array of matching …
```
> feat: official support for custom remote cache providers

- .changeset/fifty-items-shop.md
- packages/cli/src/lib/plugins/remoteCache.ts
This command should return nothing instead of `undefined` when no artifact matches.
> fix: remote-cache list returninig undefined instead of empty

- .changeset/unlucky-lobsters-hunt.md
- packages/cli/src/lib/plugins/remoteCache.ts
- packages/tools/src/lib/build-cache/fetchCachedBuild.ts
Turn off download progress from `remote-cache download` command for now
> fix: download message in remote-cache --json

- .changeset/bright-rabbits-bathe.md
- packages/cli/src/lib/plugins/remoteCache.ts
- packages/tools/src/lib/build-cache/common.ts
- packages/tools/src/lib/build-cache/github/GitHubBuildCache.ts
Add new flags to `remote-cache` command:
- `--all`: applies to `list` and `delete` actions, instructing to list/delete all matching artifacts
- `--all-but-latest`: applies to `delete`, instructing it to delete all artifacts except the latest one (first one listed)
- the `delete` action by default will only remove one latest item now
> feat: add --all flag to list and delete, --all-but-latest to delete;

- .changeset/seven-starfishes-cheat.md
- packages/provider-github/src/lib/artifacts.ts
Convert warning to error. This requires user action, so it's better to fail fast. Plus people seem to omit warnings pretty often.
|before|after|
|--|--|
|<img width="833" alt="image" src="https://github.com/user-attachments/assets/1dbf477a-722a-4e3e-87c0-49b732473530" />|<img width="713" alt="image" src="https://github.com/user-attachments/assets/4101c4f3-4d22-41ac-8708-4d5dbf8e24c3" />|
> chore: throw instead of warn when token is invalid

- .changeset/lucky-jobs-taste.md
- packages/cli/src/lib/cli.ts
- packages/config/src/lib/config.ts
- packages/platform-apple-helpers/src/lib/commands/build/buildOptions.ts
- packages/platform-apple-helpers/src/lib/commands/build/buildProject.ts
- packages/platform-apple-helpers/src/lib/commands/build/createBuild.ts
- packages/platform-apple-helpers/src/lib/commands/run/createRun.ts
- packages/platform-apple-helpers/src/lib/commands/run/getBuildSettings.ts
- packages/platform-apple-helpers/src/lib/index.ts
- packages/platform-apple-helpers/src/lib/types/index.ts
- packages/platform-apple-helpers/src/lib/utils/buildApp.ts
- packages/platform-apple-helpers/src/lib/utils/destionation.ts
- packages/platform-apple-helpers/src/lib/utils/getPlatformInfo.ts
- packages/plugin-brownfield-ios/src/lib/pluginBrownfieldIos.ts
- packages/plugin-metro/src/lib/start/command.ts
- packages/plugin-metro/src/lib/start/runServer.ts
- packages/plugin-repack/src/lib/pluginRepack.ts
- packages/tools/src/lib/dev-server/findDevServerPort.ts
- website/docs/docs/cli.md
- website/docs/docs/getting-started/introduction.md
- website/docs/docs/getting-started/migrating-from-community-cli.mdx
Scope:
- unify `--destination` and `--destinations` flags for Apple platforms. Now it's single `--destination` flag that accepts either `simulator|device` or xcodebuild destination values.
- fix building universal (device+simu) iOS brownfield framework
Resolves #320
> feat: unify --destination and --destinations flags Apple platforms

- .github/workflows/nightly.yml
Use matrix strategy to simplify the nightly configs (metro/repack x ios/android)
> chore: simplify nightly configs

- .changeset/yellow-mangos-chew.md
- website/docs/docs/getting-started/migrating-from-community-cli.mdx
> docs: add update scripts step to RNC CLI migration guide 

- .changeset/hungry-worms-hammer.md
- packages/config/package.json
- packages/create-app/package.json
- packages/platform-android/package.json
- packages/platform-apple-helpers/package.json
- packages/platform-ios/package.json
- packages/plugin-brownfield-android/package.json
- packages/plugin-brownfield-ios/package.json
- packages/plugin-metro/package.json
- packages/plugin-repack/package.json
- packages/provider-github/package.json
- packages/provider-s3/package.json
- packages/test-helpers/package.json
- packages/tools/package.json
With `require(ESM)` available in newer node version there is no reason to artificially limit importing through ESM imports only - to reflect that, I've changed the `import` condition to `default` which will always be taken into account regardless of how packages are imported.
cc @satya164 
n/a
> chore: use `default` condition everywhere in package exports

- .changeset/thin-melons-shave.md
- packages/platform-apple-helpers/src/lib/utils/buildApp.ts
When `udid` or `name` are available, we should always set these instead of generic destination for `xcodebuild`.
cc @mdjastrzebski @troZee
> fix: bring back using id/name before setting generic destination

- .changeset/pink-trees-wonder.md
- packages/config/src/lib/config.ts
fix: support file:// URLs for ESM config loading on Windows (fixes #313)
This PR ensures that ESM config files are loaded using file:// URLs instead of Windows paths, solving the ERR_UNSUPPORTED_ESM_URL_SCHEME error when running `rnef start` on Windows. This allows Metro and the CLI to work correctly in test apps on Windows.
Issue: https://github.com/callstack/rnef/issues/313
1. Build the branch with `pnpm build`.
2. In a test app on Windows, link local RNEF packages:
`pnpm link @rnef/cli @rnef/platform-android @rnef/platform-ios @rnef/plugin-metro`
4. Run `pnpm rnef start` in the test app.
5. Metro dev server should start without ERR_UNSUPPORTED_ESM_URL_SCHEME.
Before:
After:
> fix: use file:// URLs for ESM config on Windows

- .changeset/giant-toys-film.md
- packages/platform-apple-helpers/src/lib/commands/run/createRun.ts
- packages/provider-github/src/lib/artifacts.ts
Set a bit more information when GitHub fails to fetch for some reason.
> chore: throw more information when fetch github fails

- .changeset/selfish-trains-wash.md
- packages/cli/src/lib/plugins/logConfig.ts
When calling `config`, the native dependencies getters are invoked twice: first for the filtering pass, and then for stringily. Changed the filtering logic to push resolved getters of native deps instead of removing non-native dependencies.
Overall, this should improve config and fingerprint perf a little.
> perf: avoid double invoking of native deps in config command

- .changeset/poor-lions-carry.md
- packages/platform-apple-helpers/src/lib/commands/run/getBuildSettings.ts
- packages/platform-apple-helpers/src/lib/utils/buildApp.ts
Fixes saving to local cache with custom `--build-folder` as it wasn't respected by the `getBuildSettings` helper.
> fix: set build-folder for build settings as well

- .changeset/curly-cups-float.md
- packages/provider-s3/src/lib/providerS3.ts
Support `remote-cache delete --all-but-latest` flag for S3 provider (where it means to not delete at all)
> fix: don't delete from s3 if --all-but-latest is provided

- .changeset/fifty-donkeys-joke.md
- packages/cli/src/lib/plugins/fingerprint.ts
We don't need to show null sources (which, if I understand correctly, are due to excluded sources like node_modules), so filtering them out from the output.
When in `--raw` we'll now display the sources as JSON in stderr so we can still use stdout for scripting and display the sources for debugging purposes.
> fix: filter null fingerprint sources; output sources to stderr when --raw

- .changeset/shiny-apes-rhyme.md
- packages/tools/src/lib/hermes.ts
Related to #404
After conducting several tests, I discovered an issue with the previous implementation. While the previous PR excluded `debugId` insertion (considering it Sentry's responsibility), it turns out to be necessary.
**Root Cause**: Even when the original source map contains a `debugId`, it gets lost during the compose sourcemap process.
The `debugId` follows the TC39 Stage 2 proposal specification:
https://github.com/tc39/ecma426/blob/main/proposals/debug-id.md
I've also verified that Expo handles `debugId` processing and included their implementation as reference:
https://github.com/expo/expo/blob/997aefa7271a9fd49f83beba541b8026bb8592ae/packages/%40expo/metro-config/src/serializer/serializeChunks.ts#L499-L511
When using Hermes bytecode compilation, the source map composition …
> feat: extract and inject debugId in hermes sourcemaps

- website/docs/docs/remote-cache/github-actions/configuration.md
Added documentation on optimizing GitHub Actions workflows using `paths-ignore` to the remote cache configuration guide. 
The documentation includes:
- Explanation of benefits for using paths-ignore
- Example YAML configurations for both standard repos and
monorepos
- Best practices for implementing path filters effectively
1. Review the added documentation in
`website/docs/docs/remote-cache/github-actions/configuration.md`
2. Verify that the examples are correct and follow GitHub
Actions syntax
3. Validate that the information is clear and actionable for
users
4. Check that the document builds correctly in the documentation
site
addresses #417
> docs: added guideline for path ignore in github actions

- .changeset/tender-readers-confess.md
- packages/provider-github/src/lib/artifacts.ts
We can provide a better error when GitHub fails with 404, which may mean the user provided token with incompatible permissions.
> feat: handle 404 from github gracefully

- .changeset/quick-pianos-draw.md
- packages/platform-android/src/lib/commands/signAndroid/command.ts
- packages/platform-apple-helpers/src/lib/commands/sign/modifyApp.ts
- packages/platform-apple-helpers/src/lib/index.ts
- packages/platform-ios/src/lib/commands/signIos.ts
- website/docs/docs/cli.md
Adds `--app` flag to `sign:ios` command, allowing it to modify the .app files with a new bundle, when passed with `--build-jsbundle` or `--jsbundle` flags.
Usage:
```
rnef sign:ios --app <path-to-release-app-file> --build-jsbundle
```
Not entirely happy with the naming, as there's no signing for iOS in this case.
Fixes #405
> feat: add `--app` flag to `sign:ios` to support replacing js bundle in APP files

- .changeset/pink-jobs-destroy.md
- .npmrc
- packages/create-app/src/lib/templates.ts
- packages/create-app/src/lib/utils/prompts.ts
- packages/plugin-brownfield-ios/template/package.json
Pass `required: false` to clack's `multiselect` so that we can allow for empty selection. Without that, brownfield plugin is essentially required, which is a regression.
Additionally I've updated the `@callstack/react-native-brownfield` dependency to latest (fixes a bug), and added Android brownfield plugin.
> fix: make brownfield plugin optional; update dep; add android

- .changeset/moody-adults-help.md
- packages/provider-github/src/lib/artifacts.ts
This PR provides a fix for the CLI, which - when run without the user logged in - prints the below message containing outdated links leading to a 404 page:
- verify the link is valid
> fix: cli broken links to docs

- .changeset/swift-months-cover.md
- packages/tools/src/lib/fingerprint/index.ts
Projects using `react-native-config` library will add `ios/tmp.xcconfig` file that they instruct to git-ignore. Since it's a popular library, I'm adding it to default excludes.
Next step would be to read gitignore and apply patterns from there
> fix: add ios/tmp.xcconfig from react-native-config to fingerprint ignores

- .changeset/great-oranges-exist.md
- website/src/docs/cli.md
Adding documentation for `remote-cache` which we use for CI scripts.
> docs: add docs for remote-cache command

- .changeset/modern-ears-fetch.md
- packages/welcome-screen/package.json
Assets are non-TS so `tsc` doesn't copy them. Let's do that manually in the build script
Run build, and see assets being copied
> fix: assets not available in welcome-screen

- .changeset/tricky-mangos-confess.md
- packages/provider-github/src/lib/artifacts.ts
When I developed e2e tests for RN Legal, I was suggested to use a new script `remote-cache download` instead of downloading the artefact by myself.
I wanted to list all the artefacts locally, but the script went into an infinite loop. After a short investigation, it turned out that the script fetches 100 elements from GitHub and goes to the second iteration of the loop. The problem is that the URL is set outside the loop body, and there is no chance to change the page, so the script always fetches the first page and gets stuck in an infinite loop.
**prerequisites**
1. User must have more than 100 elements in cache, or change `PAGE_SIZE` constant from `artifacts.ts` from `provider-github` package. 
2. The GH cache must be set up in a project.
**test steps**
1. Run `npx rnef remote-cache …
> fix: infinite loop while fetching more than one page in remote-cache list-all command

- .changeset/tidy-sloths-run.md
- packages/provider-s3/package.json
- packages/provider-s3/src/lib/providerS3.ts
- pnpm-lock.yaml
- website/src/docs/configuration.md
Add support for:
- IAM roles (EC2, ECS, Lambda) via default AWS SDK provider chain
- AWS Profile via `config.profile` and `fromIni()`
- IAM Role assumption (STS) via `config.roleArn` and `fromTemporaryCredentials()`
- AWS SSO via profile + AWS CLI login
- `credential_process` handled automatically via AWS SDK
Still gotta test this. cc @DavidCMurphy - mind taking a look?
> feat: support more options for AWS S3 auth

- .changeset/eleven-buckets-joke.md
- packages/platform-apple-helpers/src/lib/commands/build/createBuild.ts
Scheme is passed as argument in brownfield setup, and without this the outputPath for the framework will be undefined.
cc @andrei-zgirvaci
> fix: get scheme from args if available

- .changeset/open-towns-tease.md
- package.json
- packages/tools/package.json
- pnpm-lock.yaml
Upgrade @clack/prompts to latest stable. 
Spinners and loaders work
> chore: bump clack prompts to 0.11

- .changeset/thick-onions-trade.md
- packages/tools/src/lib/build-cache/getBinaryPath.ts
fixes:
we can't execute `git clean -xdf` in the directory which is not git repo.
> fix: skip git clean -xdf --dry-run check if not git repo

- .changeset/seven-wings-rule.md
- packages/provider-github/src/lib/config.ts
- packages/tools/src/lib/build-cache/getBinaryPath.ts
Avoid checking "null" git remote and make the warning more approachable with link to the docs on remote cache.
> chore: update no git remote warning

- .changeset/angry-donkeys-feel.md
- packages/create-app/src/lib/utils/getPkgManager.ts
- packages/create-app/src/lib/utils/initInExistingProject.ts
- packages/create-app/src/lib/utils/migrateRnefProject.ts
We want to have 2 ways of inferring package manager: 
- from user agent (when creating app from scratch)
- from lock file (when initing in existing RNC CLI project or migrating from RNEF)
> fix(create-app): get package manager from lock correctly

- .changeset/happy-parrots-return.md
- .vscode/extensions.json
- packages/platform-apple-helpers/src/lib/commands/build/createBuild.ts
- packages/platform-apple-helpers/src/lib/commands/run/createRun.ts
- packages/platform-apple-helpers/src/lib/utils/buildApp.ts
- packages/tools/src/lib/build-cache/common.ts
- packages/tools/src/lib/build-cache/getBinaryPath.ts
- packages/tools/src/lib/fingerprint/index.ts
when running `run:ios` in new project it shouldn't give any warnings, especially related to fingerprint. 
this PR adds `ios/x.xcworkspace` to default ignore paths and adds running the fingerprint once again after pod install was run—as it most likely changes the fingerprint—and before saving to cache. This way, next time a user runs the `run:ios` or `build:ios` commands they'll have a cache hit (which doesn't happen currently)
> fix: make sure new ios project has properly configured iOS options

- .changeset/yummy-lions-wait.md
- packages/platform-android/src/lib/commands/runAndroid/runAndroid.ts
- packages/platform-android/template/android/app/src/main/res/values/styles.xml
Avoid the "Failed: install and launch" message when multiple Android devices are available but not connected.
> fix: run only on connected Android devices

- .changeset/puny-papers-wink.md
- packages/create-app/src/lib/bin.ts
when in create-app user didn't choose any plugins, let's skip adding the plugins property
before:
```js
import { platformIOS } from '@rock-js/platform-ios';
import { platformAndroid } from '@rock-js/platform-android';
import { pluginMetro } from '@rock-js/plugin-metro';
export default {
plugins: [
],
bundler: pluginMetro(),
platforms: {
ios: platformIOS(),
android: platformAndroid(),
},
remoteCacheProvider: null,
};
```
after:
```js
import { platformIOS } from '@rock-js/platform-ios';
import { platformAndroid } from '@rock-js/platform-android';
import { pluginMetro } from '@rock-js/plugin-metro';
export default {
bundler: pluginMetro(),
platforms: {
ios: platformIOS(),
android: platformAndroid(),
},
remoteCacheProvider: null,
};
```
> fix(create-app): use compact format for empty plugins array

- .changeset/sweet-apples-camp.md
- packages/cli/src/lib/plugins/fingerprint.ts
- packages/tools/src/lib/fingerprint/index.ts
Previous implementation only took env keys into a hash, so changing the env wouldn't affect the fingerprint. This PR changes it in a way that the env information is now recorded as an object of keys and values:
```
{
"type": "json",
"key": "json:env",
"hash": "8488bb5c4dea64136b0047436ee14d7f8d45b919",
"json": {
"ABC": "[HASHED:ba7816bf]",
"S3_ACCESS_KEY_ID": "[HASHED:512aa3ca]",
"S3_SECRET_ACCESS_KEY": "[HASHED:12fad43b]"
}
},
```
To make it safe when debugging on CI, we're now also hashing the values
> fix: properly take env value into account; hash sensitive data
