.changeset/cyan-penguins-learn.md, packages/create-app/src/lib/bin.ts, packages/create-app/src/lib/utils/parse-cli-options.ts, packages/create-app/src/lib/utils/prompts.ts
```
┌  Welcome to React Native Enterprise Framework!
│
◇  What is your app named?
│  asdf
│
◇  What platforms do you want to start with?
│  ios, android
│
◇  Which bundler do you want to use?
│  metro
│
◇  Which remote cache provider do you want to use?
│  GitHub Actions
│
◇  Do you want to install dependencies?
│  Yes
│
◇  Applied template, platforms and plugins
│
◇  Installed dependencies with npm
│
◇  Git repo initialized
│
◇  Next steps ─────────────────────────────────────╮
│                                                  │
│  cd asdf                                         │
│  npm run start      starts dev server            │
│  npm run ios        builds and runs iOS app      │
│  npm run android    builds and runs Android app  │
│ …
```
=> chore: add install deps to create-app flow

package.json
I need to run `pnpm install` for every PR like this #213. Let's do it automatically and make sure the lock file is ok when reviewing.
=> chore: install deps after changeset version

pnpm-lock.yaml, website/docs/index.md, website/package.json, website/rspress.config.ts
Add footer to website and link to quick start
=> docs: add callstack copyright and quick start

packages/plugin-brownfield-android/package.json, packages/plugin-brownfield-ios/package.json
=> fix: mark brownfield plugins as public for publishing

.changeset/soft-pots-cover.md, packages/platform-apple-helpers/src/lib/commands/run/getBuildSettings.ts
We need to allow for framework wrapper extension. Fixes #308
=> fix: allow framework as wrapper extension

.changeset/cyan-rice-buy.md, packages/plugin-metro/src/lib/start/command.ts, website/docs/docs/cli/index.md
Add kebab-case aliases for start commands that are camelCase for consistency.
=> chore: add kebab-case aliases for start command

.changeset/cyan-actors-joke.md, packages/platform-android/src/lib/commands/runAndroid/tryInstallAppOnDevice.ts
Fixes https://github.com/callstack/rnef/issues/316
=> feat: retry installing android app when insufficient storage

website/docs/docs/brownfield/ios.md
=> docs: improve brownfield docs

.changeset/khaki-coins-drive.md, pnpm-lock.yaml, website/package.json, website/rspress.config.ts
=> chore: add Sitemap plugin to docs

.github/workflows/nightly.yml
Extend nightly jobs with `build-android-repack` and `build-ios-repack` to test for repack support.
Manual run of this job: https://github.com/callstack/rnef/actions/runs/15190499720
=> chore: add repack to nightly build (iOS & Android)

.changeset/little-sheep-return.md, packages/provider-github/src/lib/getGitRemote.ts
This warning is not really necessary anymore.
=> chore: drop 'No git remote found' warning

.changeset/healthy-tigers-punch.md, packages/platform-android/template/android/app/build.gradle
=> feat: turn on R8 by default in release

.changeset/swift-garlics-jump.md, packages/provider-s3/README.md, packages/provider-s3/package.json, packages/provider-s3/src/__tests__/providerS3.test.ts, packages/provider-s3/src/lib/providerS3.ts, pnpm-lock.yaml, website/docs/docs/configuration.md
The links generated by the S3 provider are now accessible. Duration time of the link is configurable and defaults to 24h.
=> feat: support presigned links in s3 provider

.github/workflows/ci.yml
Incorrect options passed to license-kit
=> chore: fix license-kit setup

.github/workflows/ci.yml
Fixes the Check Licenses GitHub Action by correcting an incorrect command in the workflow file.
=> fix: broken check licenses GitHub Action step

.changeset/new-buses-hear.md, packages/cli/package.json, packages/platform-android/package.json, packages/platform-apple-helpers/package.json, packages/platform-ios/package.json, packages/plugin-brownfield-android/package.json, packages/plugin-brownfield-ios/package.json, packages/plugin-metro/package.json, pnpm-lock.yaml
=> chore: update RNC CLI to 19.1 for RN 0.80 compat

nx.json
=> chore: disable Nx terminal UI

website/theme/styles.css
Before:
https://github.com/user-attachments/assets/d96cb074-6110-4ff5-8841-10ad41205cfd
After:
https://github.com/user-attachments/assets/bb7a129e-0bc4-4701-b48e-30f978406303
Open the website, only loaded font should be visible.
=> docs: add `font-display: block`

.changeset/weak-wasps-invite.md, website/src/docs/brownfield/android.md
This PR updates docs for Android brownfield integration. Specifically, this PR adds steps required for integration with `expo`.
https://github.com/user-attachments/assets/e9a0adf9-ca55-4b5f-ab0d-a1ae9d25bead
=> docs: add steps required for expo

website/src/docs/configuration.md
=> docs: include fingerprint.config.js

.changeset/selfish-mugs-hammer.md, packages/cli/src/lib/plugins/remoteCache.ts, packages/tools/src/lib/build-cache/common.ts
Fixes regression after introducing new UI and spinner for fingerprint calculation.
=> fix: remote-cache in json mode

website/src/docs/brownfield/ios.mdx
Add a warning mentioning the error to guide users towards solution for issues like #474
=> docs(brownfield): mention copying ReactBrownfield in step 6

.changeset/young-toys-grab.md, packages/cli/src/lib/plugins/remoteCache.ts
=> fix: check for args.binaryPath before bailing with no app.tar.gz

.changeset/small-mice-wear.md, packages/create-app/src/lib/bin.ts, packages/create-app/src/lib/steps/git-init.ts, packages/create-app/src/lib/utils/getPkgManager.ts, packages/create-app/src/lib/utils/initInExistingProject.ts, packages/platform-android/src/lib/commands/buildAndroid/command.ts, packages/platform-android/src/lib/commands/generateKeystore.ts, packages/platform-android/src/lib/commands/getValidProjectConfig.ts, packages/platform-android/src/lib/commands/runAndroid/command.ts, packages/platform-android/src/lib/platformAndroid.ts, packages/platform-ios/src/lib/platformIOS.ts
Support initialization in existing projects with `create-app` package.
```
cd RNCCLIApp
pnpm create @rnef/app
```
=> feat: init in existing project

templates/rock-template-default/package.json
- Failing build: https://github.com/callstack/rock/actions/runs/17057978883
- Fixed build: https://github.com/callstack/rock/actions/runs/17063424958
=> fix: nightly build 2025-08-19

.changeset/three-kings-check.md, README.md, packages/cli/README.md, packages/create-app/README.md
Fixes some old commands syntax
=> docs: update create-app readmes

.changeset/good-tigers-study.md, packages/cli/package.json, packages/config/package.json, packages/create-app/package.json, packages/platform-android/package.json, packages/platform-apple-helpers/package.json, packages/platform-ios/package.json, packages/plugin-brownfield-android/package.json, packages/plugin-brownfield-ios/package.json, packages/plugin-metro/package.json, packages/plugin-repack/package.json, packages/provider-github/package.json, packages/provider-s3/package.json, packages/tools/package.json, packages/welcome-screen/package.json, templates/rock-template-default/package.json
Add missing information to cross-link between npm and GitHub
=> chore: add repository informatino for npm

.changeset/huge-grapes-write.md, package.json, pnpm-lock.yaml, website/package.json
=> chore: update node types to 20
